name: Update YouTube Feed

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install feedparser
        run: pip install feedparser

      - name: Fetch all videos, sort, and build index.html
        run: |
          python3 - <<'EOF'
          import feedparser
          from datetime import datetime
      
          ids = []
          with open('channels.txt') as f:
              for line in f:
                  line = line.strip().split()[0]
                  if line:
                      ids.append(line)
          print(f"Found channel IDs: {ids}")
      
          videos = []
          for cid in ids:
              d = feedparser.parse(f'https://www.youtube.com/feeds/videos.xml?channel_id={cid}')
              if d.entries:
                  print(f"Found {len(d.entries)} videos for channel {cid}")
                  for entry in d.entries:
                      if "/shorts/" in entry.link:
                          print(f"Skipping short: {entry.link}")
                          continue
                      published_dt = datetime.strptime(entry.published, "%Y-%m-%dT%H:%M:%S%z")
                      videos.append((published_dt, entry.yt_videoid))
              else:
                  print(f"No videos found for channel {cid}")
      
          # Sort newest first
          videos.sort(key=lambda x: x[0], reverse=True)
      
          html = """<!DOCTYPE html>
          <html><head><title>YouTube Feed</title></head><body>
          <h1>My YouTube Feed</h1>"""
          for _, vid in videos:
              html += f'<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/{vid}?rel=0" allowfullscreen></iframe><br>'
          html += "</body></html>"
      
          print(f"Writing {len(videos)} videos to index.html")
          open('index.html','w').write(html)
          EOF
      
            

      - name: Commit and push
        run: |
          git config user.name "pimk3"
          git config user.email "pimk3@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/pimk3/youtube-static-feed-template.git"
      
          git add index.html
          git commit -m "Update videos $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin HEAD:main || echo "Push failed"

